### ISSUE TITLE
Change matrix orientation

### ISSUE THREAD

**Issue by rofinn** [invenia/Impute.jl#23]
From #17

**Comment by rofinn** [comment]
This should probably happen separately from the existing deprecations release.

**Comment by nickrobinson251** [comment]
Should have a `dims` keyword?

**Comment by rofinn** [comment]
I'd rather not provide the option to minimize confusion.

**Comment by rofinn** [comment]
Based on a recommendation from Curtis I've introduced a `vardim` kwarg to the `Imputor` constructors and imputation convenience functions. The `vardim` field in the `Imputor` is ignored unless we're operating on matrices.

**Comment by nickrobinson251** [comment]
Since we usually operate on each variate in turn (not each observation) it makes sense for variates to be in columns by default?

Neither JuliaStats nor Invenia have consistent orientation across all packages, I suggest the best way forward is "do what the computer likes"; AFAIU Julia stored arrays in column-major, so acting column-by-column is usually faster than row-by-row, so let's have the thing we operate on most be the thing in the columns for any given package, and let's offer a `dims`/`obsdims`/`vardims` keyword for being explicit and flexible?

**Comment by rofinn** [comment]
That's true, but we already do that with tables. I don't expect people to be applying univariate methods to matrices as often as tables. In the future we'll have methods that only work on matrices using MultivariateStats.jl and Distributions.jl.
